# yaml-language-server: $schema=https://www.authelia.com/schemas/latest/json-schema/configuration.json
theme: "auto"

server:
  address: 'tcp://:80/'

totp:
  disable: true

webauthn:
  disable: true

duo_api:
  disable: true

ntp:
  disable_startup_check: true

authentication_backend:
  password_change:
    disable: true

  password_reset:
    disable: true
    custom_url: "https://tug.org/memberpassword.cgi"

  refresh_interval: "always"

  file:
    path: "/config/users_database.yml"
    watch: true
    extra_attributes:
      id:
        value_type: "integer"

access_control:
  default_policy: "deny"
  rules:
    - domain: ["tug.org", "*.tug.org"]
      policy: "one_factor"
      subject: "group:member"

session:
  cookies:
      - name: "authelia_session"
        domain: "tug.org"
        authelia_url: "https://authelia.tug.org/"

# Password retry lockouts
regulation:
  modes: ["user", "ip"]

storage:
  encryption_key: '{{ fileContent "/secrets/storage_encryption_key" | trim }}'
  local:
    path: '/config/db.sqlite3'

notifier:
  filesystem:
    filename: '/config/notification.txt'

identity_providers:
  oidc:
    hmac_secret: '{{ fileContent "/secrets/identity_providers_oidc_hmac_secret" | trim }}'

    jwks:
      - key: |
          {{- fileContent "/secrets/identity_providers_oidc_jwks_key" | nindent 10 }}

    clients:
        - client_id: "lychee"
          client_secret: '{{ fileContent "/secrets/identity_providers_oidc_clients_client_secret" | trim }}'

          authorization_policy: "one_factor"

          consent_mode: "implicit"

          token_endpoint_auth_method: "client_secret_post"

          redirect_uris:
            - 'https://photos.tug.org/auth/authelia/redirect'

          scopes:
            - "openid"
            - "groups"
            - "email"
            - "profile"
